### ISSUE TITLE
directory spelling

### ISSUE THREAD

**Issue by nixinator** [DarthPJB/NixOS-Configuration#1]
you missed an n in

environments

a bet you hate me now.

how does one do a pull request on a directory rename, i know git hates stuff like this...... perhaps it doesn't hate it so much these days?

**Comment by DarthPJB** [comment]
rename (or move) :

`git mv <old name> <new name>`

So, workflow is: 

1. Fork Repo
2. Make change (using git mv)
3. Make sure the configuration still works (how many times did i reference that folder :O)
4. git commit / git push 
5. Make pull request 
6. Profit

**Comment by DarthPJB** [comment]
> you missed an n in
> 
> environments
> 
> a bet you hate me now.
> 
> how does one do a pull request on a directory rename, i know git hates stuff like this...... perhaps it doesn't hate it so much these days?
rename (or move) :

git mv <old name> <new name>

So, workflow is:

    Fork Repo
    Make change (using git mv)
    Make sure the configuration still works (how many times did i reference that folder :O)
    git commit / git push
    Make pull request
    Profit

**Comment by DarthPJB** [comment]
this change will be brought in when the flake update is completed
